  master:
    datasource:
      type: com.zaxxer.hikari.HikariDataSource
      driverClassName: com.mysql.jdbc.Driver
      jdbcUrl: jdbc:mysql://abitree.cze6qhvun9td.ap-northeast-1.rds.amazonaws.com:3306/abitree?autoReconnect=true&useSSL=false
#      url: jdbc:mysql://abitreedb.cze6qhvun9td.ap-northeast-1.rds.amazonaws.com:3306/abitree?autoReconnect=true&useSSL=false
      username: abitree
      password: Abitree0
      testOnBorrow: true
      validationInterval: 34000
      validationQuery: SELECT 1
      maximum-pool-size: 2
      minimum-idle: 1
  slave:
    datasource:
      type: com.zaxxer.hikari.HikariDataSource
      driverClassName: com.mysql.jdbc.Driver
      jdbcUrl: jdbc:mysql://abitree.cze6qhvun9td.ap-northeast-1.rds.amazonaws.com:3306/abitree_read?autoReconnect=true&useSSL=false
#      url: jdbc:mysql://abitreedb.cze6qhvun9td.ap-northeast-1.rds.amazonaws.com:3306/abitree?autoReconnect=true&useSSL=false
      username: abitree
      password: Abitree0
      testOnBorrow: true
      validationInterval: 34000
      validationQuery: SELECT 1
      maximum-pool-size: 2
      minimum-idle: 1
      read-only: true


